### ISSUE TITLE
Lack of dependency for hr_cae_contract

### ISSUE THREAD

**Issue by quentinDupont** [odoo-cae/odoo-addons-hr-incubator#32]
With a clean install for hr_cae_contract I have an error for creating new contract :
`'hr.employee' object has no attribute 'turnover_minimum'` (same for date_start)
It's looking for `turnover_minimum` which is a field defined in hr_cae.
I tried to add the dependency but II get more issues so i didn't go further

**Comment by legalsylvain** [comment]
OK. This problem could be detected because travis is configured to test each module separately. [ref](https://github.com/odoo-cae/odoo-addons-hr-incubator/blob/12.0/.travis.yml#L21).

However, the installation is OK, but it fails when you execute specific actions.

Improving coverage could raise such errors. 

@mclaeysb could you take a look on this issue ? 

It comes from this line : https://github.com/odoo-cae/odoo-addons-hr-incubator/blob/12.0/hr_cae_contract/models/hr_contract.py#L363

thanks !

**Comment by mclaeysb** [comment]
There's a dependency missing on `hr_cae` here. This opens a wider question: in this case it's clearly missing because a field from `hr_cae` is called. In other `hr_cae_...` modules, the need to load `hr_cae` is not strict. Should it be there, as the module name suggests, or should the modules be renamed?

Wrt adding tests: I don't know of a way to test `@api.onchange` in v12.

@legalsylvain could you explain why Travis didn't detect this?

**Comment by legalsylvain** [comment]
> @legalsylvain could you explain why Travis didn't detect this?

well, Travis is set in a unittest context to make sure all the module are installable and works separately.
Howerver, 
- it is possible to install the module ``hr_cae_contract`` (it will not fail)
- Tests are passing, because the function is not called.

Regarding onchange test, maybe you could take a look on existing OCA tests. 
executing a ``rgrep "def .*test.*onchange" ./ --include=*.py`` returns several exemples

for exemple this one : 

https://github.com/OCA/social/blob/12.0/mail_activity_team/tests/test_mail_activity_team.py#L87

kind regards.

**Comment by mclaeysb** [comment]
Thanks a lot for that clear answer @legalsylvain !

> There's a dependency missing on `hr_cae` here. This opens a wider question: in this case it's clearly missing because a field from `hr_cae` is called. In other `hr_cae_...` modules, the need to load `hr_cae` is not strict. Should it be there, as the module name suggests, or should the modules be renamed?

@robinkeunen Your opinion on this?

**Comment by robinkeunen** [comment]
I think `hr_cae_contract` should depend on `hr_cae`, they're clearly linked since `hr_cae` contains the base models.

For other modules, I'd leave the prefix as we develop all of this in the context of integrating new people in a CAE. But no need to add dependencies where not needed.

**Comment by mclaeysb** [comment]
Fixed with 8bb0f99ab0d79d12e7a8df6c38d99ae233abb330

**Comment by legalsylvain** [comment]
Sinon, y'a /ocabot ;-)
